// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"github/linchao0828/messengerBot/biz/dal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Config{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Config{}) fail: %s", err)
	}
}

func Test_configQuery(t *testing.T) {
	config := newConfig(db)
	config = *config.As(config.TableName())
	_do := config.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(config.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <config> fail:", err)
		return
	}

	_, ok := config.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from config success")
	}

	err = _do.Create(&model.Config{})
	if err != nil {
		t.Error("create item in table <config> fail:", err)
	}

	err = _do.Save(&model.Config{})
	if err != nil {
		t.Error("create item in table <config> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Config{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <config> fail:", err)
	}

	_, err = _do.Select(config.ALL).Take()
	if err != nil {
		t.Error("Take() on table <config> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <config> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <config> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <config> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Config{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <config> fail:", err)
	}

	_, err = _do.Select(config.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <config> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <config> fail:", err)
	}

	_, err = _do.Select(config.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <config> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <config> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <config> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <config> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Config{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <config> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <config> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <config> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <config> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <config> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <config> fail:", err)
	}
}
