// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "post"

// Post mapped from table <post>
type Post struct {
	ID            int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	PostID        int64     `gorm:"column:post_id;type:bigint(20) unsigned;not null;uniqueIndex:idx_pid,priority:1" json:"post_id"`
	UserID        int64     `gorm:"column:user_id;type:bigint(20) unsigned;not null" json:"user_id"`
	Type          int32     `gorm:"column:type;type:tinyint(4) unsigned;not null" json:"type"`
	Content       *string   `gorm:"column:content;type:text" json:"content"`                                   // markdown format content
	MentionUserID string    `gorm:"column:mention_user_id;type:varchar(1024);not null" json:"mention_user_id"` // user_id json array
	ReplyPostID   int64     `gorm:"column:reply_post_id;type:bigint(20) unsigned;not null" json:"reply_post_id"`
	CreatedTime   time.Time `gorm:"column:created_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime   time.Time `gorm:"column:updated_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_time"`
	DeletedTime   time.Time `gorm:"column:deleted_time;type:timestamp;not null;default:2038-01-19 03:14:07" json:"deleted_time"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
