// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int64     `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id;type:bigint(20) unsigned;not null;uniqueIndex:idx_uid,priority:1" json:"user_id"`
	Email        string    `gorm:"column:email;type:varchar(128);not null" json:"email"`
	Password     string    `gorm:"column:password;type:varchar(256);not null" json:"password"`
	PasswordSalt string    `gorm:"column:password_salt;type:varchar(32);not null" json:"password_salt"`
	Nickname     string    `gorm:"column:nickname;type:varchar(36);not null" json:"nickname"`
	AvatarKey    string    `gorm:"column:avatar_key;type:varchar(512);not null" json:"avatar_key"`
	CreatedTime  time.Time `gorm:"column:created_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_time"`
	UpdatedTime  time.Time `gorm:"column:updated_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
